#!/bin/bash

# Set the SERVER_ENV_CONFIG (from rancher.env) and
# SERVER_ENV_CONFIG_SECRET (from rancher.env.gpg) in server environment files
# Before the the odoo V 11.0 we should set the env file variables on the project not on cloud-platforme
echo "Odoo version > 10, script ignored"
