customer_name: cosanum
odoo_version: '14.0'
customer_shortname: cosanum
repo_name: cosanum_odoo
project_id: '2477'
project_name: cosanum_odoo
odoo_company_name: Cosanum
odoo_main_lang: de_DE
odoo_aux_langs: fr_CH;it_IT
platform_name: ch
